services:
  typer:
    image: "typer:1.0"
    ports:
      - "55555:80"
  healthcheck:
    image: "healthcheck:1.0"
    environment:
      MOCK_HOST: "mock.user.website.fi"
      MOCK_PORT: "80"
      DATA_HOST: "typer.website.fi"
      DATA_PORT: "443"
      SCRAP_HOST: "scraper"
      SCRAP_PORT: "5000"
    restart: always
    ports:
      - "5000:5000"
  scraper:
    image: "scraper:1.0"
    environment:
      PROTOCOL: "http"
      MOCK_HOST: "mock.user.website.fi"
      MOCK_PORT: "80"
    ports:
      - "1337:5000"