apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mock
  name: mock-deployment
spec:
  replicas: 1
  selector:
    app: mock
    matchLabels:
      app: mock
  template:
    metadata:
      labels:
        app: mock
        pool: mock-serve
    spec:
      containers:
      - image: "image-registry.website.fi/user/mock-website:1.0"
        name: mock
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mock
  name: mock-service
spec:
  selector:
    app: mock
    pool: mock-serve
  ports:
  - name: port-two
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: mock
  name: mock-route
spec:
  host: mock.user.website.fi
  to:
    kind: Service
    name: mock-service
  port:
   targetPort: port-two