apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: typer
  name: database-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: typer
  name: typer-deployment
spec:
  replicas: 1
  selector:
    app: typer
    matchLabels:
      app: typer
  template:
    metadata:
      labels:
        app: typer
        pool: typer-serve
    spec:
      containers:
      - image: "image-registry.website.fi/user/database:1.0"
        name: database
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: database-pvc
      volumes:
      - name: database-pvc
        persistentVolumeClaim:
          claimName: database-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: typer
  name: typer-service
spec:
  selector:
    app: typer
    pool: typer-serve
  ports:
  - name: port-one
    port: 5000
    protocol: TCP
    targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: typer
  name: typer-route
spec:
  host: typer.website.fi
  to:
    kind: Service
    name: typer-service
  port:
   targetPort: port-one
  tls:
    termination: edge